#!/usr/bin/env python3
"""Validate Agent Skills frontmatter, links, and the generated index."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "SKILL_INDEX.md"
NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
LINK_RE = re.compile(r"\[[^]]*]\(([^)]+)\)")


def parse_frontmatter(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError("missing opening YAML frontmatter delimiter")
    try:
        raw, body = text[4:].split("\n---\n", 1)
    except ValueError as exc:
        raise ValueError("missing closing YAML frontmatter delimiter") from exc

    values: dict[str, str] = {}
    for line in raw.splitlines():
        if not line.strip() or line.startswith((" ", "\t")):
            continue
        if ":" not in line:
            raise ValueError(f"invalid frontmatter line: {line!r}")
        key, value = line.split(":", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values, body


def skill_files() -> list[Path]:
    return sorted(
        path
        for path in ROOT.glob("*/SKILL.md")
        if ".git" not in path.parts
    )


def render_index(skills: list[tuple[str, str]]) -> str:
    lines = [
        "<!-- Generated by scripts/validate_skills.py --write-index. -->",
        "",
        "| Skill name | Description |",
        "| --- | --- |",
    ]
    for name, description in skills:
        lines.append(f"| `{name}` | {description.replace('|', '&#124;')} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write-index", action="store_true")
    args = parser.parse_args()

    errors: list[str] = []
    catalog: list[tuple[str, str]] = []

    for path in skill_files():
        try:
            frontmatter, body = parse_frontmatter(path)
        except ValueError as exc:
            errors.append(f"{path.relative_to(ROOT)}: {exc}")
            continue

        name = frontmatter.get("name", "")
        description = frontmatter.get("description", "")
        if not NAME_RE.fullmatch(name):
            errors.append(f"{path.relative_to(ROOT)}: invalid skill name {name!r}")
        if name != path.parent.name:
            errors.append(
                f"{path.relative_to(ROOT)}: name must match directory {path.parent.name!r}"
            )
        if not description or len(description) > 1024:
            errors.append(
                f"{path.relative_to(ROOT)}: description must contain 1-1024 characters"
            )
        compatibility = frontmatter.get("compatibility")
        if compatibility is not None and not 1 <= len(compatibility) <= 500:
            errors.append(
                f"{path.relative_to(ROOT)}: compatibility must contain 1-500 characters"
            )
        catalog.append((name, description))

        for target in LINK_RE.findall(body):
            clean = target.split("#", 1)[0]
            if not clean or "://" in clean or clean.startswith(("mailto:", "#")):
                continue
            if not (path.parent / clean).resolve().exists():
                errors.append(f"{path.relative_to(ROOT)}: broken link {target!r}")

    expected = render_index(sorted(catalog))
    if args.write_index:
        INDEX.write_text(expected, encoding="utf-8")
    elif not INDEX.exists() or INDEX.read_text(encoding="utf-8") != expected:
        errors.append("SKILL_INDEX.md is stale; run validator with --write-index")

    for directory in ROOT.glob("*/**/*"):
        if directory.is_dir() and directory.name in {"assets", "references", "scripts"}:
            if not any(directory.iterdir()):
                errors.append(f"{directory.relative_to(ROOT)}: empty resource directory")

    if errors:
        print("\n".join(f"ERROR: {error}" for error in errors), file=sys.stderr)
        return 1
    print(f"Validated {len(catalog)} skills.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
